Visit.delete_all
Site.delete_all
User.delete_all

puts "Seeding users..."
matt = User.create!(username: "matt", password: "123")
mike = User.create!(username: "mike", password: "123")
ann = User.create!(username: "ann", password: "123")

puts "Seeding sites..."
petes_tavern = Site.create!(name: "Pete's Tavern", lat: 40.73653, lng: -73.986746, description: "Pete's Tavern, located at the corner of 18th Street and Irving Place in the Gramercy Park neighborhood of Manhattan, New York City, is a pub food restaurant and one of several drinking establishments each claiming to be the oldest continuously operated tavern in the city.\nThe building that houses Pete's was built in 1829, and was originally the Portman Hotel; liquor may have been sold there as early as 1851 or 1852 - when it was a 'grocery & grog' store - and the first official drinking establishment founded by 1864. It was bought in 1899 by Tom and John Healy, and became Healy's. During prohibition, when selling alcohol was illegal, the bar continued to operate disguised as a flower shop.\nThe writer O. Henry lived down the street at 55 Irving Place from 1903 to 1907, and Healy's appears in his short story 'The Lost Blend' under the name 'Kenealy's'. Local legend also has it that he wrote his well-known story 'The Gift of the Magi' in Healy's second booth from the front, but this appears to be apocryphal.\nThe present name dates to the purchase of the establishment by Peter Belles in 1926.\nAlthough the tavern claims to be 'an official historical landmark', it is neither a designated New York City landmark nor is it on the National Register of Historic Places. It does, however, lie within the Gramercy Park Historic District designated by the New York City Landmarks Preservation Commission in 1966.", category: "Food/Drink")
statue_of_liberty = Site.create!(name: "Statue of Liberty", lat: 40.689167, lng:  -74.044444, description: "'The Statue of Liberty Enlightening the World' was a gift of friendship from the people of France to the United States and is recognized as a universal symbol of freedom and democracy. The Statue of Liberty was dedicated on October 28, 1886.  It was designated as a National Monument in 1924.  Employees of the National Park Service have been caring for the colossal copper statue since 1933.", category: "Object")
central_park = Site.create!(name: "Central Park", lat: 40.782222, lng: -73.965278, description: "Central Park is an urban park in New York City, between the Upper West and Upper East Sides of Manhattan. It is the fifth largest park in the city, covering 843 acres (341 ha). It is the most visited urban park in the United States, with an estimated 42 million visitors annually as of 2016, and is the most filmed location in the world.", category: "Nature")
fraunces = Site.create!(name: "Fraunces Tavern", lat: 40.703333, lng: -74.011389, description: "Fraunces Tavern is a museum and restaurant in New York City, situated at 54 Pearl Street at the corner of Broad Street in the Financial District of Lower Manhattan. The location played a prominent role in history before, during, and after the American Revolution. At various points in its history, Fraunces Tavern served as a headquarters for George Washington, a venue for peace negotiations with the British, and housing federal offices in the Early Republic.\nFraunces Tavern has been owned since 1904 by Sons of the Revolution in the State of New York Inc., which carried out a major conjectural reconstruction, and claim it is Manhattan's oldest surviving building. The museum interprets the building and its history, along with varied exhibitions of art and artifacts. The tavern is a tourist site and a part of the American Whiskey Trail and the New York Freedom Trail. It is listed on the National Register of Historic Places and is a New York City designated landmark. In addition, the block on which Fraunces Tavern is located is a National Historic Landmark District and a New York City designated landmark district.", category: "Food/Drink")
dvorak = Site.create!(name: "Statue of Antonin Dvorak", lat: 40.7339, lng: -73.9823, description: "This statue by Croatian-American sculptor Ivan Mestrovic (1883-1962) honors the Czech composer Antonin Dvorak (1841-1904) who made this neighborhood his home for a time, and helped to integrate several musical traditions.\nIn 1892, Dvorak, already internationally renowned, was appointed director of the National Conservatory of Music in America, and settled for three years in New York City at 327 East 17th Street. During his stay in the United States, he was greatly influenced by African-American spirituals and Native American music. His most famous work in this period was the Symphony #9, in E Minor, better known as the New World Symphony (1893). Other notable compositions during his American tenure included the Cello Concerto (1894-95) and the Quartet in F for strings.", category: "Object")
fairgrounds = Site.create!(name: "World's Fairgrounds", lat: 40.744028, lng: -73.844417, description: "Flushing Meadows-Corona Park was home to the 1939-40 and 1964-65 New York World's Fairs. The Fairs were instrumental in the development of Flushing Meadows-Corona Park, and this playground, located along the Grand Central Parkway near 62nd Road, is one of many sites in the park existing because of the fair. Parks Commissioner Robert Moses (1888-1981) hoped to develop the site into a grand park after the 1939-40 New York World's Fair and secured the 1216-acre location in the Flushing Meadows.", category: "Events/Stories")
flatiron = Site.create!(name: "Flatiron Building", lat: 40.741111, lng: -73.989722, description: "The Flatiron Building, originally the Fuller Building, is a triangular 22-story, 285-foot-tall (86.9 m) steel-framed landmarked building located at 175 Fifth Avenue in the eponymous Flatiron District neighborhood of the borough of Manhattan, New York City. Designed by Daniel Burnham and Frederick Dinkelberg, it was one of the tallest buildings in the city upon its 1902 completion, at 20 floors high, and one of only two 'skyscrapers' north of 14th Street—the other being the Metropolitan Life Insurance Company Tower, one block east. The building sits on a triangular block formed by Fifth Avenue, Broadway, and East 22nd Street—where the building's 87-foot (27 m) back end is located—with East 23rd Street grazing the triangle's northern (uptown) peak. As with numerous other wedge-shaped buildings, the name 'Flatiron' derives from its resemblance to a cast-iron clothes iron.\nCalled 'one of the world's most iconic skyscrapers and a quintessential symbol of New York City', the building anchors the south (downtown) end of Madison Square and the north (uptown) end of the Ladies' Mile Historic District. The neighborhood around it is called the Flatiron District after its signature, iconic building. The building was designated a New York City landmark in 1966, was added to the National Register of Historic Places in 1979, and was designated a National Historic Landmark in 1989.", category: "Architecture")


puts "Seeding visits..."
petes_tavern.visits.create!(user: matt, rating: 4, comment: "Was pretty cool, had some drinks.")
central_park.visits.create!(user: matt, rating: 5, comment: "Was great! Lots of amazing birds.")
central_park.visits.create!(user: mike, rating: 3, comment: "Was a little boring, but still nice to get fresh air.")
statue_of_liberty.visits.create!(user: ann, rating: 0, comment: "Overcrowded.")
fraunces.visits.create!(user: ann, rating: 5, comment: "Such a cool historical place!")
fraunces.visits.create!(user: mike, rating: 5, comment: "Yummmm!")
dvorak.visits.create!(user: matt, rating: 5, comment: "This is where it all happened!")
fairgrounds.visits.create!(user: ann, rating: 4, comment: "I liked the model of NYC in the museum.")
flatiron.visits.create!(user: mike, rating: 3, comment: "Cool looking building, but nothing to do inside.")

puts "Seeding complete!"